
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const ADD_DISCOUNT = "ADD_DISCOUNT";
const REMOVE_DISCOUNT = "REMOVE_DISCOUNT";

export {ADD_TO_CART, REMOVE_FROM_CART, ADD_DISCOUNT, REMOVE_DISCOUNT};
